'use strict';
// Fills ordinary fields from a reviewed pack. The applicant uploads documents, answers every
// declaration and clicks the employer's submit button. This file never clicks submit.
const $=s=>document.querySelector(s);
async function api(path,body){const r=await fetch('http://127.0.0.1:8765'+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+$('#token').value,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const result=await r.json();if(!r.ok)throw Error(JSON.stringify(result));return result}
async function activeTab(){const [tab]=await chrome.tabs.query({active:true,currentWindow:true});return tab}
async function fill(){const job_id=$('#job').value.trim();try{const pack=await api('/pack?job_id='+encodeURIComponent(job_id));const tab=await activeTab();if(!pack.adapter||!pack.gate_passed||pack.match_score<80)throw Error('Approved adapter and matching gates required');if(new URL(tab.url).href!==new URL(pack.adapter.exact_url).href)throw Error('Active page does not match approved exact URL');const filled=await chrome.scripting.executeScript({target:{tabId:tab.id},func:fillForm,args:[pack]});const value=filled[0]?.result;if(!value?.ok)throw Error(value?.error||'Form fill failed');await api('/attempt',{job_id});$('#status').textContent='Fields filled. '+(value.left.length?'Answer these yourself: '+value.left.join(', ')+'. ':'')+'Upload the documents, check everything and submit it yourself. Then press Record result.'}catch(e){$('#status').textContent=e.message}}
async function record(){const job_id=$('#job').value.trim();try{const pack=await api('/pack?job_id='+encodeURIComponent(job_id)).catch(()=>null);const tab=await activeTab();let result={status:'uncertain',receipt:''};if(pack&&pack.adapter){const out=await chrome.scripting.executeScript({target:{tabId:tab.id},func:readReceipt,args:[pack.adapter]});result=out[0]?.result||result}await api('/result',{job_id,...result});$('#status').textContent=result.status==='submitted'?'Receipt captured and recorded.':'No receipt found: recorded as uncertain. Reconcile it before any retry.'}catch(e){$('#status').textContent=e.message}}
async function notSent(){const job_id=$('#job').value.trim();try{await api('/result',{job_id,status:'failed',receipt:'Applicant did not submit'});$('#status').textContent='Recorded as not submitted.'}catch(e){$('#status').textContent=e.message}}
function fillForm(pack){try{if(location.href!==pack.adapter.exact_url)throw Error('Page mismatch');if(Date.now()-Date.parse(pack.verified_at)>900000)throw Error('Vacancy verification expired');const a=pack.adapter;if(!a.reviewed||!Array.isArray(a.fields))throw Error('Adapter not reviewed');const DECL=/right_to_work|sponsor|visa|work_permit|authori[sz]|criminal|conviction|caution|clearance|vetting|conflict|health|disab|equal|gender|ethnic|religio|sexual|declar|consent|confirm|fitness|safeguard/i;let ops=[],left=[];for(const f of a.fields){const list=document.querySelectorAll(f.selector);if(list.length!==1)throw Error('Selector missing or ambiguous: '+f.selector);const el=list[0];if(f.declaration||DECL.test(f.key)||['checkbox','radio'].includes(el.type)){el.style.outline='3px solid #d97706';left.push(f.key);continue}if(!['INPUT','TEXTAREA','SELECT'].includes(el.tagName)||['password','file','submit','hidden'].includes(el.type))throw Error('Unsupported field');if(el.disabled||!el.getClientRects().length)throw Error('Field unavailable');const value=f.key==='cover_letter'?pack.cover_letter:pack.profile[f.key];if(value===undefined||value===null||value==='')throw Error('Answer missing: '+f.key);if(el.tagName==='SELECT'&&!Array.from(el.options).some(o=>o.value===String(value)))throw Error('Option unavailable');ops.push([el,String(value)])}for(const [el,value]of ops){const proto=el.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:el.tagName==='SELECT'?HTMLSelectElement.prototype:HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value').set.call(el,value);el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}))}return {ok:true,left}}catch(e){return {ok:false,error:e.message}}}
function readReceipt(a){try{const el=document.querySelector(a.receipt_selector);const text=el&&el.getClientRects().length?el.textContent.trim():'';if(text&&new RegExp(a.receipt_pattern).test(text))return {status:'submitted',receipt:location.href+' | '+text.slice(0,1500)};return {status:'uncertain',receipt:''}}catch(e){return {status:'uncertain',receipt:''}}}
if(typeof chrome!=='undefined'&&chrome.tabs){$('#fill').onclick=fill;$('#record').onclick=record;$('#notsent').onclick=notSent}
